\documentclass{article}

\begin{document}

\begin{tabular}{ |p{2cm}||p{1.5cm}|p{2cm}|{p2cm}|{p2cm}|{p2cm}|{p2cm}|{p2cm}  }
 \hline
 \multicolumn{8}{|c|}{Videography Summary Statistics} \\
 \hline
 Section & Min & 1st Quartile & Mean & Median & 3rd Quartile & Max & K\\
 \hline
 Morning & 7 & 16.75 & 20.13 & 22  & 25 & 29 & -0.6\\
 Afternoon & 14 & 24.75 &  32.25 & 31 & 42 & 49 & -1.3\\
 \hline
\end{tabular}


\end{document}